name: run-tsc-on-pull-request
on: [push, pull_request]

jobs:
  run-typescript-compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./react-app
      - run: npx tsc
        working-directory: ./react-app